/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cn.tinyhai.android

import kotlin.test.Test

/**
 * A simple unit test for the 'cn.tinyhai.android.modules.config.greeting' plugin.
 */
class AndroidConfigPluginPluginTest {
    @Test fun `plugin registers task`() {
//        // Create a test project and apply the plugin
//        val project = ProjectBuilder.builder().build()
//        project.plugins.apply("cn.tinyhai.android.modules.config.greeting")
//
//        // Verify the result
//        assertNotNull(project.tasks.findByName("greeting"))
    }
}
