/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cn.tinyhai.android.plugin

import cn.tinyhai.android.dsl.TinyhaiScoped
import org.gradle.api.Plugin
import org.gradle.api.Project

class TinyhaiPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        TinyhaiScoped.setup(project)
        project.afterEvaluate(AfterEvaluated)
    }
}
